sudo: required
language: java
jdk:
  - oraclejdk8
script:
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - ./gradlew build distDocker
    - docker tag albertonavarro/recordserver:travis_"$TRAVIS_BUILD_NUMBER" albertonavarro/recordserver:readytotest
    - docker push albertonavarro/recordserver:readytotest
    - ./gradlew deploy_tools:waitUntilDeployed -P deploy_endpoint="$TEST_SERVER"/info -P deploy_expected_version=travis_"$TRAVIS_BUILD_NUMBER"
    - ./gradlew integration-test:test -DrecordserverUrl=http://recordserver.trafalgar.ws:8081 -Dlazylogin.url=http://lazylogin.trafalgar.ws:8081 -Dremote=true --stacktrace
    - docker tag albertonavarro/recordserver:travis_"$TRAVIS_BUILD_NUMBER" albertonavarro/recordserver:readyforprod
    - docker push albertonavarro/recordserver:readyforprod
    - ./gradlew deploy_tools:waitUntilDeployed -P deploy_endpoint="$PROD_SERVER"/info -P deploy_expected_version=travis_"$TRAVIS_BUILD_NUMBER"
    - ./gradlew integration-test:test -DrecordserverUrl=http://recordserver.trafalgar.ws:8080 -Dlazylogin.url=http://lazylogin.trafalgar.ws:8080 -Dremote=true --stacktrace
services:
  - docker

